# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 14:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('location_latlng', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('location_webmercator', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('border_latlng', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('border_webmercator', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
            ],
        ),
    ]
