# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 15:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
